config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'

  resources :products do
    resources :reviews
  end

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :cost, presence:true
  validates :country_of_origin, presence:true, length: { maximum: 100}
  validates :grocery_category, presence:true, length: { maximum: 100}
  validates :name, presence:true, length: { maximum: 100}
  before_save(:titelize_product)

  private
    def titelize_product
      self.name = self.name.titleize
      self.country_of_origin = self.country_of_origin.titleize
      self.grocery_category = self.grocery_category.titleize
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :author, presence: true, length: { maximum: 100 }
  validates :content_body, presence: true, length: { minimum: 50, maximum: 1000 }
  validates :rating, presence: true, numericality: {less_than: 6, greater_than: -1}
  validates :product_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def authorize
    if !current_user
      flash[:alert] = "You aren't authorized to visit that page."
      redirect_to '/'
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authorize, only: [:new, :create, :edit, :update, :destroy]

  def index
    # Code for listing all products goes here.
    @products = Product.all
    @reviews = Review.all
    @products_most_reviews = []
    product_ids_of_reviews = @reviews.map do |review|
      review.product_id
    end

    @products_most_recently_reviewed = @reviews.order(created_at: :desc).limit(3).map do |review|
      @products.find(review.product_id)
    end
    @products_usa_made = @products.where("country_of_origin = 'United States' ")
    render :index
  end

  def new
    # Code for new product form goes here.
    @product = Product.new
    render :new
  end

  def create
    # Code for creating a new product goes here.
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully created."
      redirect_to products_path
    else
      flash[:notice] = "Something went wrong.  Product not successfully created."
      render :new
    end
  end

  def edit
    # Code for edit product form goes here.
    @product = Product.find(params[:id])
    render :edit
  end

  def show
    # Code for showing a single product goes here.
    @product = Product.find(params[:id])
    render :show
  end

  def update
    # Code for updating a product goes here.
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    # Code for deleting a product goes here.
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:cost, :country_of_origin, :grocery_category, :name)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authorize, only: [:new, :create, :edit, :update, :destroy]

  # def index
  #   # Code for listing all reviews goes here.
  # end

  def new
    # Code for new review form goes here.
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    # Code for creating a new review goes here.
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review successfully created."
      redirect_to product_path(@product)
    else
      flash[:notice] = "Something went wrong.  Review not successfully created."
      render :new
    end
  end

  def edit
    # Code for edit review form goes here.
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def show
    # Code for showing a single review goes here.
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def update
    # Code for updating an review goes here.
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy
    # Code for deleting an review goes here.
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end

  private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating, :product_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You've successfully signed up!"
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing up."
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix the below errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li>
        <%= message %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :country_of_origin %>
  <%= f.text_field :country_of_origin %>
  <%= f.label :grocery_category %>
  <%= f.text_field :grocery_category %>
  <%= f.label :cost %>
  <%= f.number_field :cost %>
  <%= f.submit %>
<% end %>

app/views/layouts/_review_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.label :content_body %>
  <%= f.text_field :content_body %>
  <%= f.label :product_id %>
  <%= f.number_field :product_id %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodee Review</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <% if current_user %>
      <%= current_user.email %>(<%= ( current_user.admin === true ? "Admin" : "User" ) %>) | <%= link_to "Sign out", '/signout' %>
    <% else %>
      <%= link_to "Sign up", 'signup' %> | <%= link_to "Sign in", '/signin' %>
    <% end %>

  <%= flash[:alert] %>
  <%= flash[:notice] %>
  <h1>Foodee Review</h1>
  <%= yield %>
</body>
</html>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "layouts/product_form" %>

app/views/products/index.html.erb
<% if @products.any? %>
  <div class="product-list">
    <h2>Products</h2>
    <ul>
      <% @products.each do |product| %>
      <li>
        <%= link_to product.name, product_path(product) %>
      </li>
      <% end %>
    </ul>
  </div>
  <div class="products-most-reviews">
    <h2>Products with the Most Reviews:</h2>
    <ul>
      <% @products_most_reviews.each do |product| %>
      <li>
        <%= link_to product.name, product_path(product) %>
      </li>
      <% end %>
    </ul>
  </div>
  <div class="products-most-recently-reviewed">
    <h2>Products Most Recently Reviewed:</h2>
    <ul>
      <% @products_most_recently_reviewed.each do |product| %>
      <li>
        <%= link_to product.name, product_path(product) %>
      </li>
      <% end %>
    </ul>
  </div>
  <div class="products-usa-made">
    <h2>Products Made in the USA:</h2>
    <ul>
      <% @products_usa_made.each do |product| %>
      <li>
        <%= link_to product.name, product_path(product) %>
      </li>
      <% end %>
    </ul>
  </div>
<% else %>
  <p>
    There are no products in the database.
  </p>
<% end %>

<p>
  <%= link_to "Add new product", new_product_path %>
</p>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "layouts/product_form" %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h3>Grocery Category: <%= @product.grocery_category %></h3>
<h3>Cost: <%= @product.cost %></h3>
<h3>Country of Origin: <%= @product.country_of_origin %></h3>

<% if @product.reviews.any? %>
<h4>Reviews:</h4>
<% @product.reviews.each do |review| %>
<ul>
  <li>
    <%= link_to review.author, product_review_path(@product, review) %>
  </li>
</ul>
<% end %>
<% else %>
<p>No reviews are listed for this product.</p>
<% end %>

<% if current_user %>
  <p><%= link_to "Add a review", new_product_review_path(@product) %></p>
  <% if current_user.admin %>
    <p><%= link_to "Edit", edit_product_path(@product) %></p>
    <p><%= link_to "Delete", product_path(@product),
    :data => {:confirm => "Are you sure you want to delete this product?",
    :method => "delete"} %></p>
  <% end %>
<% end %>
<p><%= link_to "Return to products", products_path %></p>

app/views/reviews/edit.html.erb
<h1>Edit review:</h1>

<%= render "layouts/review_form" %>

app/views/reviews/new.html.erb
<h1>Add a review:</h1>

<%= render "layouts/review_form" %>

app/views/reviews/show.html.erb
<h1>Review By: <%= @review.author %></h1>
<h2>Product: <%= @product.name %></h2>
<h3><%= @review.rating %></h3>

<p>"<%= @review.content_body %>"</p>


<% if current_user %>
  <% if current_user.admin %>
    <p><%= link_to "Edit review", edit_product_review_path(@product, @review) %></p>
    <p><%= link_to "Delete review", product_review_path(@product, @review),
      :data => {:confirm => "Are you sure you want to delete this review?",
      :method => "delete"} %></p>
  <% end %>
<% end %>
<p><%= link_to "Return to Product", product_path(@product) %></p>

app/views/users/new.html.erb
<h1> Sign up</h1>
<%= form_for @user do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.label :admin %>
  <%= f.check_box :admin %>  
  <%= f.submit "Sign Up" %>
<% end %>